project:
  type: website
  output-dir: docs

website:
  title: "Albert Ramon Jr"
  navbar:
   background: primary
   left:
      - text: Home 
        href: index.qmd
      - text: Bio
        href: bio.qmd
      - text: Media Releases
        href: mediareleases.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
   page-footer:
    left: "Copyright 2023, Albert Ramon"


format:
  html:
    theme:
      light: lux
      dark: cyborg
    css: styles.css
editor: visual


