---
editor: visual 
title: "Resume"
---

[Resume PDF](https://docs.google.com/document/d/e/2PACX-1vQLkTTReKTP7gprVWIVyDqr5msEhvMGwfoUaJshCNPkoO711GmLvznS0u87fGZzVA/pub)

Education

*Master of Business Administration*

*Expected May 2023*

Atkinson Graduate School of Management --- Willamette University

*Highlighted Coursework: Marketing Research, Data Analytics, Data Science for Strategic Applications, Finance, Communicating with Data*

*Bachelor of Science, Physics*

*Highlighted Coursework: Multivariable Calculus, Python, Computer Science, Data Analysis, Quantum Physics*

Experience

FedEx Ground, Chino, CA

Logistics and Transportation Intern

● Analyzed SLP data analysis and presented local trend data to senior level management by showing distribution optimization and efficiency improvements.

● Developed a trailer dwell time program using Excel BA that processes and organizes data to assist management in determining the root causes of trailers not making service.

● Projected the main Hub goals over the fiscal year for 2023 identifying breakdowns in organizational communication and processes through managing interviews, then recommended and implemented changes expediting internal workflow by one week.

Willamette University

Student Research Laboratory Assistant

● Collaborated with a group of seven to identify, evaluate, and improve on methods for finding galaxy velocity and bulk flow. Identified and evaluated data sets and worked with excel to file, store, and organize the data. 

● Increased the test scores of my students, increasing their knowledge of physics by providing resources such as study guides, in depth figures, and charts

Information Technology Consultant

● Responsible for ensuring smooth operations and protecting and managing valuable information and data.\
● Coordinated and managed the flow of data through Google.\
● Worked with marketing concepts, local demographics, online optimization, fundraising and community partnerships.\
● Used Business Process Model and Notation to plan and manage workflow and deliverables.

\
\
